version: "3.9"
services :

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  app:
    build: pythonApp/
    ports:
      - 8000:8000
      - 8001:8001

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093
    environment:
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}

  blackbox-exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox/:/etc/blackbox_exporter/
    ports:
      - 9115:9115

  pushgateway:
    image: prom/pushgateway
    volumes:
      - ./pushgateway/:/etc/pushgateway/
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000


